version: '3'
services:
  proxy:
    build: proxy-docker/.
    ports:
     - "8080:8080"
  first:
    build: test-upstream-container/.
    environment:
     - CONTAINER_ID=Kontti-1
  second:
    build: test-upstream-container/.
    environment:
     - CONTAINER_ID=Kontti-2
