version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
     - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, '-g', 'daemon off;']
  first:
    build: container1/.
  second:
    build: container2/.
